# fly.toml app configuration file generated for hyperbore-market-data on 2025-02-24T02:40:12-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hyperbore-market-data"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3001"
  NODE_ENV = "production"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[metrics]
  port = 3001
  path = "/metrics"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
